name: justindaniel
favicon: null
layout_spectrum: 0.33814719831570983
typography_spectrum: 0.868217213312164
title: JustinDaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e2337'
    - '#5f5a6d'
    - '#75836d'
    - '#0c5d9b'
    - '#c9ccbc'
  brandStrength: 0.8926585044246167
  lightness: 0.7162715676240623
  saturation: 0.519351789727807
  rhythmicContrast: 0.24836589209735394
purpose: []
