name: justindaniel
favicon: null
layout_spectrum: 0.33814719831570983
typography_spectrum: 0.868217213312164
title: JustinDaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#3b4443'
    - '#7d7e71'
    - '#babab8'
    - '#fefef3'
  brandStrength: 0.8926585044246167
  lightness: 0.7162715676240623
  saturation: 0.519351789727807
  rhythmicContrast: 0.24836589209735394
purpose: []
